local _, addon = ...

addon.vignetteDescriptions = {
	[4783] = "Go to Keeper's Respite and wait for Caretaker Kah-Kay to spawn (60.6, 23.2).  Speak to him to gain the Sharp-eyed buff.  Follow the purple footsteps and then click on the pile of bones to spawn Mailbog.",
	[4798] = "A Mawsworn Portal may appear after killing any other rares in Korthia.  After several waves of mobs, Towering Exterminator will spawn.",
	[4793] = "Before attacking, wait for Consumption to reach 40 stacks of the Anima Gorged buff.  This is when it will become a rare elite",
	[4800] = "A Devouring Tear (portal) may appear after killing any other rares in Korthia.  After several waves of mobs, Konthrogz the Obliterator will spawn.",
	[4810] = "Use a Repaired Riftkey to enter The Rift via any nearby Rift Portal. Once inside, click on Screaming Shade to pull them out of The Rift.",
	[4820] = "Use a Repaired Riftkey to enter The Rift via any nearby Rift Portal. Once inside, click on Silent Soulstalker to pull them out of The Rift.",
	[4822] = "Use a Repaired Riftkey to enter The Rift via any nearby Rift Portal. Once inside, click on Deadsoul Hatcher to pull them out of The Rift.",
	[4832] = "A Venthyr covenant member must speak to Drippy (nearby) to start the event. Defend the Venthyr NPCs while they repair the Broken Gatecrasher.  Eventually the Stygian Stonecrusher will spawn.",
	[4835] = "A Night Fae covenant member must play the drum to bring the Escaped Wilderling over.  Once the Escaped Wilderling has become weakened, ride it and maintain your grip.",
	[4839] = "A Kyrian covenant member must speak to Popo and escort them to where the Wild Worldcracker spawns.",
	[4841] = "A Necrolord covenant member must speak to Cadaverous (nearby) to begin.  Loot corpses in the area and bring them to the Corpse Heap to summon Fleshwing.",
	[4857] = "The Assault Supply Carriage will travel into the Maw until it reaches the Carriage Crusher.",
	[4858] = "Use a Repaired Riftkey to enter The Rift via any nearby Rift Portal.",
	[4860] = "Use a Teleporter Repair Kit to repair the Ancient Teleporter.  Once repaired, anyone can enter and access Yarxhov the Pillager's chamber.",
	[4862] = "Use a Teleporter Repair Kit to repair the Ancient Teleporter.  Once repaired, anyone can enter and access Xyraxz the Unknowable's chamber.",
	[4863] = "Located at the back of the cave.",
	[4864] = "Interact with the Uncorrupted Razorwing Egg to draw Reliwik the Defiant over.",
	[4866] = "The Abandoned Veilstaff may appear in any of several caves throughout Korthia.  Interact with it to spawn Ve'rayn.  Answer their questions until they become hostile and attack you.",
-- Zereth Mortis Rares
	[4742] = "Pull all 5 of the Bulging Roots in the area to activate the Gluttonous Overgrowth.",
	[4770] = "Keep killing the Overgrown Helicid until Orixal spawns",
	[4893] = "Collect three Energizing Leporids from the area and feed them to the nearby Hungry Nestlings to activate Garudeon.",
	[4933] = "Help The Matriarch to spawn The Engulfer",
	[4940] = "Aggro the nearby Menacing Vespoid Workers so that they will cast Paralytic Sting on you. Zatojin will come down to attack you once you have reached 20 stacks and have become Paralyzed!",
	[4941] = "Kill the two elite Mawsworn Binders that are channeling Otaris the Provoked to start the encounter.",
	[4945] = "Aggro Xy'azam or Xy'kina to activate the Corrupted Architect.",
	[4949] = "Find the three Empowered Keys in the area and use them to open the Suspiciously Angry Vault to spawn Furidian.",
	[4988] = "Find the nearby matching Mysterious Sigils (out of 4) for each of the Barrier Control Console(s) to unlock them.  This may require two people if the symbols on each console are different",
	[4984] = "Requires fishing with an Aurelid Lure to spawn Hirukon",
}
